import { CreateEvent } from "../../../../server/controller/EventController";

export default async (req, res) => {
  const {
    event_title,
    event_type,
    selectState,
    selectCity,
    event_price,
    hard_ship,
    event_summery,
    event_summery_continue,
    club_services_items,
    club_service_description,
    breakfast_service,
    lunch_service,
    dinner_service,
    mid_meal_service,
    essentialEq,
    recomendedEq,
    startEventDate,
    endEventDate,
    travel_days,
    enterance_rules,
    cancellation_rules,
    stayingLocation,
    tavel_start_description,
    entertainments,
    event_number,
    last_second,
    peak_name,
    peak_height,
    discount_code,
    recommended_list,
    discount_percent,
    register_deadline,
    event_capacity,
    event_owner,
    transfer_type,
    eventBanner,
    entertainments_Payment,
  } = req.body;
  const data = await CreateEvent({
    event_title,
    event_type,
    selectState,
    selectCity,
    event_price,
    hard_ship,
    event_summery,
    event_summery_continue,
    club_services_items,
    club_service_description,
    breakfast_service,
    lunch_service,
    dinner_service,
    mid_meal_service,
    recommended_list,
    essentialEq,
    event_capacity,
    recomendedEq,
    startEventDate,
    endEventDate,
    travel_days,
    enterance_rules,
    cancellation_rules,
    stayingLocation,
    tavel_start_description,
    entertainments,
    event_number,
    last_second,
    peak_height,
    discount_code,
    discount_percent,
    register_deadline,
    event_owner,
    peak_name,
    transfer_type,
    entertainments_Payment,
    eventBanner,
  });
  res.status(200).json(data);
};

export const config = {
  api: {
    bodyParser: {
      sizeLimit: "4mb",
    },
  },
};
